Repository 3rd-wanted-pre-onboarding-team-D/02-PayHere-wanted-D, pull requests merged in 2022-07, with the labels that each got.

#2 Setting: 프로젝트 초기 세팅 (#1)
  .eslintrc.js
  .gitignore
  .prettierrc
  ddl/DDL.sql
  nest-cli.json
  ormConfig.ts
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/entities/FinantialLedger.ts
  src/entities/Token.ts
  src/entities/User.ts
  src/main.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
  webpack-hmr.config.js
Labels: Setting

#8 Setting: ci setting with GitHub actions (#7)
  .github/workflows/ci.yml
Labels: Setting

#10 Setting: environment 추가 (#1)
  .github/workflows/ci.yml
Labels: Setting

#12 Setting: dockerfile 작성
  .dockerignore
  .github/workflows/ci.yml
  dockerfile
  ormConfig.ts
Labels: Setting

#14 Setting: deploy to aws codedeploy
  .github/workflows/aws.yml
Labels: Setting

#16 Setting: CD 구축 (#11)
  .github/workflows/aws.yml
  deploy.sh
Labels: Setting

#17 Setting: CD 구축 (#11) (#16)
  .github/workflows/aws.yml
  deploy.sh
Labels: Setting

#18 Setting: appspec.yml 추가 (#11)
  .github/workflows/aws.yml
  appspec.yml
Labels: Setting

#28 Setting: CD 구축 (#11)
  .github/workflows/aws.yml
  appspec.yml
  deploy.sh
  src/app.module.ts
Labels: Setting

#25 Feature: 가계부 작성, 조회, 상세내역
  docker-compose.dev-db.yml
  ormConfig.ts
  package-lock.json
  package.json
  src/app.module.ts
  src/entities/FinancialLedger.ts
  src/entities/User.ts
  src/financial-ledger/dto/financial-ledger.day.dto.ts
  src/financial-ledger/dto/financial-ledger.dto.ts
  src/financial-ledger/dto/financial-ledger.group.dto.ts
  src/financial-ledger/dto/financial-ledger.list.dto.ts
  src/financial-ledger/dto/financial-ledger.response.dto.ts
  src/financial-ledger/dto/financial-ledger.write.dto.ts
  src/financial-ledger/financial-ledger.controller.ts
  src/financial-ledger/financial-ledger.module.ts
  src/financial-ledger/financial-ledger.repository.ts
  src/financial-ledger/financial-ledger.service.spec.ts
  src/financial-ledger/financial-ledger.service.ts
  src/financial-ledger/interceptor/financial-ledger.interceptor.ts
  src/main.ts
Labels: Feat

#24 Feature: 가계부 수정, 삭제, 복구
  .gitignore
  ddl/DDL.sql
  docker-compose.test-db.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/jwt.strategy.ts
  src/entities/FinancialLedger.ts
  src/financial-ledger/__test__/financial-ledger.fixture.ts
  src/financial-ledger/__test__/financial-ledger.service.spec.ts
  src/financial-ledger/__test__/financial-ledger.service.unit.spec.ts
  src/financial-ledger/__test__/user.fixture.ts
  src/financial-ledger/dto/update-request.dto.ts
  src/financial-ledger/financial-ledger.controller.ts
  src/financial-ledger/financial-ledger.service.spec.ts
  src/financial-ledger/financial-ledger.service.ts
  src/main.ts
  src/setSwagger.ts
  test/app.e2e-spec.ts
  test/financial-ledger.e2e-spec.ts
  test/utils/access-token.ts
  test/utils/clear-database.ts
  test/utils/typeorm-test-config.ts
Labels: Feat, Test

#30 Setting: test 코드 추가로 인한 ci 재구성
  .github/workflows/ci.yml
Labels: Setting

#35 Setting: typeorm 옵션 수정
  ormConfig.ts
Labels: Setting

#42 Test: 가계부 조회 테스트코드 리팩토링 (#41)
  src/financial-ledger/__test__/financial-ledger.service.spec.ts
  src/financial-ledger/financial-ledger.repository.ts
Labels: Test

#44 Update: 유저 API 스웨거 설정 수정 (#43)
  src/common/dto/response/common-response.dto.ts
  src/common/interceptors/response.interceptor.ts
  src/users/dto/request/log-in-body.dto.ts
  src/users/dto/request/sign-up-body.dto.ts
  src/users/dto/response/common/response-token-logout.dto.ts
  src/users/dto/response/common/response-token.dto.ts
  src/users/users.controller.ts
Labels: Refactor, Test
